#!/bin/bash

set -x

if [ "$#" -ne 2 ]; then
     echo "usage ./watch [game] [mapid]"
     exit 1
fi

DEMO=JT_
WAD=~/doom/
case $1 in
     "d1")
          DEMO+=Doom1
          WAD+=doom.wad
          ;;
     "d2")
          DEMO+=Doom2
          WAD+=doom2.wad
          ;;
     "tnt")
          DEMO+=TNT
          WAD+=tnt.wad
          ;;
     "*")
          echo "unknown game. see help."
          exit 1
          ;;
esac

DEMO+=_$2

~/repos/cndoom-2.0.3.2/src/cndoom -playdemo demos/$DEMO -iwad $WAD
